[build]
  publish = "dist"
  command = "npm run build"

[dev]
  framework = "#auto"
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200